#配置端口
server:
  port: 8888
  servlet:
    context-path: /

spring:
  application:
    name: tool
  servlet:
    multipart:
      max-file-size: 50000000000
      max-request-size: 200000000000
  jackson:
    serialization:
      write-dates-as-timestamps: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/itools?serverTimezone=GMT%2b8&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: Aa@11111111
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

